# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = [".", "./derive"]

[package]
name = "openapi_type"
version = "0.2.3"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
description = "OpenAPI type information for Rust structs and enums"
keywords = ["openapi", "type"]
license = "Apache-2.0"
repository = "https://github.com/msrd0/openapi_type"
readme = "crates-io.md"
include = ["src/**/*", "LICENSE", "crates-io.md"]

[dependencies]
indexmap = "1.7"
openapi_type_derive = { path = "./derive", version = "0.2.4" }
openapiv3 = "=0.4.0"
serde_json = "1.0"

# optional dependencies / features
chrono = { version = "0.4.19", default-features = false, optional = true }
uuid = { version = "0.8.2" , optional = true }

[dev-dependencies]
paste = "1.0"
pretty_assertions = "0.7"
serde = { version = "1.0", features = ["derive"] }
trybuild = "1.0"
